site_name: xscript

nav:
  - 主页: index.md
  - xscript如何工作: howto.md
  - 是否应该选择xscript: choose-xscript.md
  - 报告BUG: bug.md
  - 学习xscript:
    - 目录: learn/index.md
    - 安装xscript: learn/install.md
    - 基本输入输出: learn/basic-io.md
    - 更漂亮的界面: learn/colorful.md
    - 使用debug: learn/use-debug.md
    - 自定义标准库: learn/config-lib.md
  - xscript标准库:
    - 索引: lib/index.md
    - file: lib/file.md
    - random: lib/random.md
    - table: lib/table.md
    - time: lib/time.md
    - turtle: lib/turtle.md
    - ui: lib/ui.md
    - util: lib/util.md

theme: readthedocs

copyright: Copyright &copy 2020 jason-bowen-zheng<br>All Right Reserved.

markdown_extensions:
  - admonition
