site_name: xscript

nav:
        - 主页: index.md
        - 学习xscript: learn.md
        - xscript如何工作: howto.md
        - xscript标准库:
          - 索引: lib.index.md
          - file: lib/file.md
          - math: lib/math.md
          - random: lib/random.md
          - string: lib/string.md
          - time: lib/time.md
          - turtle: lib/turtle.md
          - ui: lib/ui.md
          - util: lib/util.md
          - var: lib/var.md
        - 报告BUG: bug.md

theme: readthedocs

copyright: Copyright &copy 2020 jason-bowen-zheng<br>All Right Reserved.
